let d1 = document.querySelector(".d1")
let d2 = document.querySelector(".d2")
let d3 = document.querySelector(".d3")
let d4 = document.querySelector(".d4")
let l1 = document.querySelector(".l1")
let l2 = document.querySelector(".l2")
let l3 = document.querySelector(".l3")
let l4 = document.querySelector(".l4")
let l5 = document.querySelector(".l5")
let l6 = document.querySelector(".l6")

d2.addEventListener("click", function(){
    d2.classList.remove("blue")
    d2.classList.add("red") 
    d1.classList.add("blue") 
    d3.classList.add("blue") 
    d4.classList.add("blue") 
    d1,d4,d3.classList.remove("red")
})
d1.addEventListener("click", function(){
    d1.classList.remove("blue")
    d1.classList.add("red") 
    d2.classList.add("blue") 
    d3.classList.add("blue") 
    d4.classList.add("blue") 
    d2,d4,d3.classList.remove("red")
})

d3.addEventListener("click", function(){
    d3.classList.remove("blue")
    d3.classList.add("red") 
    d2.classList.add("blue") 
    d1.classList.add("blue") 
    d4.classList.add("blue") 
    d1,d4,d2.classList.remove("red")
})
d4.addEventListener("click", function(){
    d4.classList.remove("blue")
    d4.classList.add("red") 
    d2.classList.add("blue") 
    d3.classList.add("blue") 
    d1.classList.add("blue") 
    d1,d2,d3.classList.remove("red")
})

l1.addEventListener("click", function(){
    l1.classList.add("brd")
    l1.classList.remove("nobrd")
    l2.classList.remove("brd")
    l3.classList.remove("brd")
    l4.classList.remove("brd")
    l5.classList.remove("brd")
    l6.classList.remove("brd")
    l2.classList.add("nobrd")
    l3.classList.add("nobrd")
    l4.classList.add("nobrd")
    l5.classList.add("nobrd")
    l5.classList.add("nobrd")
    l6.classList.add("nobrd")
})
l2.addEventListener("click", function(){
    l2.classList.add("brd")
    l2.classList.remove("nobrd")
    l1.classList.remove("brd")
    l3.classList.remove("brd")
    l4.classList.remove("brd")
    l5.classList.remove("brd")
    l6.classList.remove("brd")
    l1.classList.add("nobrd")
    l3.classList.add("nobrd")
    l4.classList.add("nobrd")
    l5.classList.add("nobrd")
    l5.classList.add("nobrd")
    l6.classList.add("nobrd")
})
l3.addEventListener("click", function(){
    l3.classList.add("brd")
    l3.classList.remove("nobrd")
    l1.classList.remove("brd")
    l2.classList.remove("brd")
    l4.classList.remove("brd")
    l5.classList.remove("brd")
    l6.classList.remove("brd")
    l1.classList.add("nobrd")
    l2.classList.add("nobrd")
    l4.classList.add("nobrd")
    l5.classList.add("nobrd")
    l5.classList.add("nobrd")
    l6.classList.add("nobrd")
})
l4.addEventListener("click", function(){
    l4.classList.add("brd")
    l4.classList.remove("nobrd")
    l1.classList.remove("brd")
    l2.classList.remove("brd")
    l3.classList.remove("brd")
    l5.classList.remove("brd")
    l6.classList.remove("brd")
    l1.classList.add("nobrd")
    l2.classList.add("nobrd")
    l3.classList.add("nobrd")
    l5.classList.add("nobrd")
    l5.classList.add("nobrd")
    l6.classList.add("nobrd")
})
l5.addEventListener("click", function(){
    l5.classList.add("brd")
    l5.classList.remove("nobrd")
    l1.classList.remove("brd")
    l2.classList.remove("brd")
    l4.classList.remove("brd")
    l3.classList.remove("brd")
    l6.classList.remove("brd")
    l1.classList.add("nobrd")
    l2.classList.add("nobrd")
    l4.classList.add("nobrd")
    l3.classList.add("nobrd")
    l6.classList.add("nobrd")
})
l6.addEventListener("click", function(){
    l6.classList.add("brd")
    l6.classList.remove("nobrd")
    l1.classList.remove("brd")
    l2.classList.remove("brd")
    l4.classList.remove("brd")
    l5.classList.remove("brd")
    l3.classList.remove("brd")
    l1.classList.add("nobrd")
    l2.classList.add("nobrd")
    l4.classList.add("nobrd")
    l5.classList.add("nobrd")
    l5.classList.add("nobrd")
    l3.classList.add("nobrd")
})